export type Dish = {
  id: string;
  name: string;
  category: string;
  mealType: "Plato" | "Postre";
  description: string;
  price: number;
  emoji: string;
  tags: string[];
};

export const dishes: Dish[] = [
  {
    id: "milanesa",
    name: "Milanesa IPF",
    category: "Clásico",
    mealType: "Plato",
    description: "Milanesa crocante, ensalada fresca y papas doradas.",
    price: 4200,
    emoji: "🥩",
    tags: ["Popular"],
  },
  {
    id: "ravioles",
    name: "Ravioles de ricota",
    category: "Clásico",
    mealType: "Plato",
    description: "Pasta casera con salsa de tomate asado y albahaca.",
    price: 3900,
    emoji: "🍝",
    tags: ["Casero"],
  },
  {
    id: "pollo",
    name: "Pollo al horno",
    category: "Clásico",
    mealType: "Plato",
    description: "Pollo dorado con arroz primavera y jugo de hierbas.",
    price: 4100,
    emoji: "🍗",
    tags: ["Casero", "Popular"],
  },
  {
    id: "risotto",
    name: "Risotto de hongos",
    category: "Celíaco",
    mealType: "Plato",
    description: "Arroz cremoso, hongos salteados y queso parmesano.",
    price: 4300,
    emoji: "🍚",
    tags: ["Sin TACC", "Casero"],
  },
  {
    id: "empanadas",
    name: "Empanadas de carne",
    category: "Celíaco",
    mealType: "Plato",
    description: "Tres empanadas horneadas con masa certificada sin TACC.",
    price: 3600,
    emoji: "🥟",
    tags: ["Sin TACC"],
  },
  {
    id: "tortilla",
    name: "Tortilla de papas",
    category: "Celíaco",
    mealType: "Plato",
    description: "Porción de tortilla dorada con ensalada de estación.",
    price: 3300,
    emoji: "🥔",
    tags: ["Sin TACC", "Vegetariano"],
  },
  {
    id: "tarta",
    name: "Tarta de verduras",
    category: "Vegetariano",
    mealType: "Plato",
    description: "Masa integral, vegetales grillados y queso cremoso.",
    price: 3100,
    emoji: "🥧",
    tags: ["Vegetariano"],
  },
  {
    id: "ensalada",
    name: "Ensalada del día",
    category: "Vegetariano",
    mealType: "Plato",
    description: "Hojas verdes, vegetales de estación y vinagreta cítrica.",
    price: 2800,
    emoji: "🥗",
    tags: ["Veggie", "Ligero"],
  },
  {
    id: "wok",
    name: "Wok de vegetales",
    category: "Vegetariano",
    mealType: "Plato",
    description: "Vegetales salteados, noodles de arroz y salsa de soja.",
    price: 3500,
    emoji: "🍜",
    tags: ["Veggie"],
  },
  {
    id: "guiso",
    name: "Guiso de lentejas",
    category: "Clásico",
    mealType: "Plato",
    description: "Lentejas, verduras y carne en una preparación abundante.",
    price: 3800,
    emoji: "🍲",
    tags: ["Casero", "Popular"],
  },
  {
    id: "pescado",
    name: "Pescado con guarnición",
    category: "Clásico",
    mealType: "Plato",
    description: "Filet de pescado al horno con papas y ensalada fresca.",
    price: 4400,
    emoji: "🐟",
    tags: ["Ligero"],
  },
  {
    id: "polloarroz",
    name: "Pollo con arroz",
    category: "Celíaco",
    mealType: "Plato",
    description: "Pollo grillado, arroz blanco y vegetales sin TACC.",
    price: 4200,
    emoji: "🍛",
    tags: ["Sin TACC", "Casero"],
  },
  {
    id: "pastasin",
    name: "Pasta de maíz",
    category: "Celíaco",
    mealType: "Plato",
    description: "Pasta sin TACC con salsa fileto y queso rallado.",
    price: 4000,
    emoji: "🍝",
    tags: ["Sin TACC"],
  },
  {
    id: "hamburguesa",
    name: "Hamburguesa de lentejas",
    category: "Vegetariano",
    mealType: "Plato",
    description: "Medallón de lentejas, pan artesanal y vegetales crocantes.",
    price: 3600,
    emoji: "🍔",
    tags: ["Veggie", "Popular"],
  },
  {
    id: "zapallitos",
    name: "Zapallitos rellenos",
    category: "Vegetariano",
    mealType: "Plato",
    description: "Zapallitos rellenos de quinoa, verduras y queso gratinado.",
    price: 3400,
    emoji: "🥒",
    tags: ["Veggie", "Ligero"],
  },
  {
    id: "flan",
    name: "Flan casero",
    category: "Clásico",
    mealType: "Postre",
    description: "Flan de vainilla con dulce de leche y crema.",
    price: 1800,
    emoji: "🍮",
    tags: ["Dulce", "Popular"],
  },
  {
    id: "brownie",
    name: "Brownie de chocolate",
    category: "Clásico",
    mealType: "Postre",
    description: "Brownie húmedo con nueces y salsa de chocolate.",
    price: 2100,
    emoji: "🍫",
    tags: ["Dulce"],
  },
  {
    id: "cheesecake",
    name: "Cheesecake de frutos rojos",
    category: "Celíaco",
    mealType: "Postre",
    description: "Cheesecake con base sin TACC y coulis de frutos rojos.",
    price: 2400,
    emoji: "🍰",
    tags: ["Sin TACC"],
  },
  {
    id: "budin",
    name: "Budín de banana",
    category: "Celíaco",
    mealType: "Postre",
    description: "Budín húmedo de banana, sin TACC y con semillas.",
    price: 1900,
    emoji: "🍌",
    tags: ["Sin TACC", "Casero"],
  },
  {
    id: "fruta",
    name: "Ensalada de frutas",
    category: "Vegetariano",
    mealType: "Postre",
    description: "Frutas frescas de estación con jugo de naranja.",
    price: 1500,
    emoji: "🍓",
    tags: ["Veggie", "Ligero"],
  },
  {
    id: "yogur",
    name: "Yogur con granola",
    category: "Vegetariano",
    mealType: "Postre",
    description: "Yogur natural, granola crocante y miel.",
    price: 1700,
    emoji: "🥣",
    tags: ["Veggie", "Ligero"],
  },
];

export const formatPrice = (price: number) =>
  `$${price.toLocaleString("es-AR")}`;
